### ISSUE TITLE
"APP/image 디렉토리를 제거" 제안

### ISSUE THREAD

**Issue by intelliguy** [openinfradev/decapod-base-yaml#16]
본 디렉토리에는 APP/image 디렉토리를 갖고 있습니다.
이 역할은 
- 기존에 내부 이미지를 사용하기위해 이미지 재지정을 위해 이미지만 수동으로 빼어 놓은 것이었습니다.
- 그리고 내부 개발에서 내부로 옮겨놓은 이미지를 사용하도록 했었습니다.

현재 이를 사용하지 않는 방법은 
- decapod-site-yaml/$APP/$SITE/image-values.yaml을 정의하지 않고
- decapod-site-yaml/$APP/$SITE/kustomization.yaml에도 지정하지 않음으로

가능합니다.

이렇게 함으로써 장점은
- 이미지 재정의 필요시 바로 사용가능하다

단점은
- base의 chart 변경/삭제(CUD) 등에 image-values 파일을 변경해 줘야합니다.
- 또한 이를 확인할 방법은 **_commiter가 잘 하는 것 외에는 없습니다_**

현재 이미지를 이동하지 않고 tag 정보만 잘 관리하기로 한 현 시점에서 위 파일을 유지할 필요없다고 판단하여 제안합니다.

**Comment by jabbukka** [comment]
말씀하신 것처럼 현재 image-values.yaml의 관리 프로세스가 따로 없어, 값이 현행화되지 않고 outdated 될 수 있습니다.


만약 github action으로 PR시에 helm chart의 image가 image-values.yaml에 존재하는지 확인하고,
없으면 에러 메세지로 알리는 validation job이 있다면 어떨까요?
이 방법도 여전히 committer의 공수가 들어가지만.. 값이 outdated 되는 문제는 해결할 수 있지 않을까 싶습니다.

제 개인적인 의견으로는, 오프라인 사이트 구축 시마다 파일 작성 작업을 하는 것보다  
base에서 관리할 수 있다면 하는 것이 낫지 않을까 싶습니다.

**Comment by jabbukka** [comment]
@bluejayKR 약간 별개의 이슈일 수 있는데, 작년 SKB 사이트, Cast.era 사이트 구축할 때 온라인 접근이 되는 환경이었지만 private registry에 이미지를 모두 가져와서 구축했었는데 앞으로도 이런 경우가 일반적일까요?

**Comment by robertchoi80** [comment]
우선 에스더님이 말씀하신 helm chart 이미지들과 image-values 파일 비교해서 누락된 내용 확인하는건 기존에 OSH 차트 사용할 당시에 사용했었던 방법이니 참고하실 수 있을 것 같습니다.  다만 성일님 얘기하신 걸로는 chart의 default 값들을 그대로 사용할 경우 누락되는 이미지들이 있다고 하신 걸로 보아, 우리가 실제 override하는 값들을 넣었을 때 실제로 사용되는 이미지 리스트를 잘 뽑아서 해당 리스트와 image-values를 비교하던지 해야 할것 같습니다.

그리고 내부 registry를 사용하는 사이트들이 어느 정도 되는 만큼, image-values 파일을 각각의 site에서 관리한다면 더 큰 오버헤드가 될 것 같아 (chart 바뀌면 그 파일들을 모두 바꿔줘야 할테니..) 파일 자체는 base에 두되, 각 site의 kustomization.yaml 에서 해당 파일을 참조할지 말지만 선택하도록 하는게 어떨까 합니다.

**Comment by bluejayKR** [comment]
> @bluejayKR 약간 별개의 이슈일 수 있는데, 작년 SKB 사이트, Cast.era 사이트 구축할 때 온라인 접근이 되는 환경이었지만 private registry에 이미지를 모두 가져와서 구축했었는데 앞으로도 이런 경우가 일반적일까요?

구축시에는 우리가 릴리즈과정에서 "우리가 관리하는 repository"로 저장해둔 "검증된 공식"이미지들을 가지고 구축할 겁니다. 따라서, SKB나 Cast.er처럼 이 공식이미지들을 모두 가져와서 하거나, 혹은 우리가 관리하는 이미지 저장소 서비스에 접근하여 다운로드 받는 형식이 되어야 합니다. 

또 다른 측면에서는, 해당 사이트의 환경상의 문제로 다운로드에 걸리는 시간이 오래 걸리거나 쉽지 않을 경우는 가져가서 하는 경우들이 발생하기도 할 겁니다. 

따라서, 답변에 대한 대답은 "네, 가지고 가는 경우도 공식 구축 방법 충 하나여야 한다" 입니다.

**Comment by zugwan** [comment]
저도 @jabbukka 님 의견과 동일하게 'air gapped' 환경 구축 때마다 새롭게 작성하고 시행착오를 겪는 것 보다는 base에서 관리하는 것이 낫다고 생각합니다. @bluejayKR 말씀 하신 것처럼 이미지를 검증하고 보장하는 부분이 필요하다고 한다면 더욱 필요해 보입니다.

**Comment by Jaesang** [comment]
@bluejayKR 님이 `구축시에는 우리가 릴리즈과정에서 "우리가 관리하는 repository"로 저장해둔 "검증된 공식"이미지들을 가지고 구축할 겁니다.`라 하시면 @intelliguy 님의 `현재 이미지를 이동하지 않고 tag 정보만 잘 관리하기로 한 현 시점에서 위 파일을 유지할 필요없다고 판단하여 제안합니다.`라는 전제가 성립이 안되는거 같습니다. 

결국 image를 따로 관리해야한다고 이해가 되는데요

**Comment by intelliguy** [comment]
이걸 잘 관리한다면 결국 이미지의 버전이 상시 잘 관리되는 것으로 
PR의 완료시 사용이미지를 파악하고자 했던  'https://tde.sktelecom.com/pms/browse/TACODEV-590'은 필요가 없어집니다.
위 티켓(590)은 이것의 결정을 보고 진행하도록 하겠습니다.

**Comment by bluejayKR** [comment]
> @bluejayKR 님이 `구축시에는 우리가 릴리즈과정에서 "우리가 관리하는 repository"로 저장해둔 "검증된 공식"이미지들을 가지고 구축할 겁니다.`라 하시면 @intelliguy 님의 `현재 이미지를 이동하지 않고 tag 정보만 잘 관리하기로 한 현 시점에서 위 파일을 유지할 필요없다고 판단하여 제안합니다.`라는 전제가 성립이 안되는거 같습니다.
> 
> 결국 image를 따로 관리해야한다고 이해가 되는데요

두 단계인데. 

HANU프로젝트 (upstream) 입장에서는 굳이 별도로 이미지를 싱크해서 저장할 필요까지는 없다. 여기에 맞춰 최적읜 방안을 .. 
회사 입장에서는 "상용제품 릴리즈" 과정에서 위에 말한 "검증된 공식 이미지"가 필요하다. 그러니, 릴리즈 단게에서 이걸 고려해보자. 

제가 이해하기로는 성일님은 1번 단계에서의 개선방안을 제시한것이라 생각하고 있습니다.

**Comment by jabbukka** [comment]
논의한 내용을 바탕으로 다음과 같이 결론을 정리하였습니다.

### 결론
* app/image 디렉토리 및 파일은 유지한다. 
  * **프로젝트 릴리즈** 때, application에서 사용하는 모든 docker image 파일을 public registry로부터 다운로드 받아 별도로 저장한다. **docker image 리스트도 관리해야할 필요가 있다.**
  * private docker registry로부터 이미지를 사용하기 위해서는 image value를 override를 해야한다. 항상 필요한 파일은 아니지만 작년 사이트 구축 시에는 모두 image-values.yaml 파일을 사용하였다.
  * 만약 image-values.yaml이 없다면 image value override가 필요할 때마다 생성을 하고 검증해야한다. 
  결국 필요한 파일이고 생성해야한다면 base-yaml에서 공식적인 component의 일부로서 관리를 한다.
* image-values.yaml 파일을 관리하기 위한 validation job이 필요하다.

###  TO DO
* image-values.yaml validation job (_NOTE: 구현을 하며 달라질 수 있다._)
  * github action의 로직
    1. base/resources.yaml에 정의된 helm chart의 version을 기준으로 helm chart의 values.yaml에 있는 repository,  tag 값이 image/image-values.yaml에 존재하는지 확인
    2. repository, tag 값이 존재하지 않거나 upstream의 값과 다르면 "error message"를 발생시킴 => github action failed 처리
    3. 예외) **upstream 차트에 정의된 값이 아닌 특정 image를 사용하고 싶은 경우**, base/resources.yaml에 values override를 한다. value값의 우선순위는 `helm chart/values.yaml < base/resources.yaml의 value override`이다.

**Comment by jabbukka** [comment]
이 이슈는 "image 디렉토리를 제거" 하는 이슈라서 close 처리하고 새 issue를 오픈하도록 하겠습니다.
